# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='summary',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
